[package]
name = "tww"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
log = "0.4.21"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "sync"] }
wgpu = "0.20.0"
winit = "0.30.0"